//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle_data_access
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<int> engine_capacity { get; set; }
        public Nullable<int> cylinder_variant { get; set; }
        public Nullable<short> top_speed { get; set; }
        public Nullable<int> price { get; set; }
        public string image_ { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
