//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle_data_access
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_price_range
    {
        public int id { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<int> maximum { get; set; }
    }
}
